apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  selector:
    app: app-deploy
  ports:
    - port: 80
      targetPort: 5000
      nodeport: 30080
  type: NodePort
   
